### ISSUE TITLE
Setup development environment

### ISSUE THREAD

**Issue by tqvarnst** [openshift-labs/rhsummit18-cloudnative-guides#1]
A couple  of suggestions of improvements:

1. In bootstrap-dev.md we instruct the users to upload the catalog repo to the internal gogs repo. Can't we do that as part of the ansible script instead?
1. It's also unclear where the user should execute the commands at the beginning of this lab. Is it in the terminal on the local host, the bastion host? Like we agreed to the best thing would be we never ask the users to leave the Che workspace and instead have them execute commands as `oc new-project` in the Che terminal
1. We should also add `oc login` instructions to the bootstrap-dev.md for the che terminal

What do you guys think?

**Comment by siamaksade** [comment]
The instructions were written before we decide to do everything via Che. I'll update them to reflect that. Have to change the order of instructions as well 👌

**Comment by jamesfalkner** [comment]
+1 on alll that. Also need some examples of a direct URL to a service in openshift using the variable substitution. I don’t see any in the workshopper variables that allow you to construct a URL to them.

**Comment by siamaksade** [comment]
@jamesfalkner added a variable for the apps host name. Example: `http://catalog-dev.{{APPS_HOSTNAME_SUFFIX}}`
