### ISSUE TITLE
Prod automation solution missing steps for secret creation

### ISSUE THREAD

**Issue by jamesfalkner** [openshift-labs/rhsummit18-cloudnative-guides#2]
The steps for lab-5: https://github.com/openshift-labs/rhsummit18-cloudnative-guides/blob/master/bootstrap-prod.md have a few commands for creating secrets for the Jenkins credentials for the pipeline. The solution code at https://github.com/openshift-labs/rhsummit18-cloudnative-labs/blob/master/solutions/lab-5/solve.yml has no such corresponding commands.

**Comment by siamaksade** [comment]
Fixed
